name: liionpack
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - plotly
  - openpyxl
  - tqdm
  - networkx
  - jupyter
  - sympy
  - ipython
  - pip:
    - pybamm
    - lcapy
    - scikit-spatial
    - ray