name: liionpack
dependencies:
  - python
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - plotly
  - openpyxl
  - tqdm
  - networkx
  - jupyter
  - sympy
  - ipython
  - wrapt
  - sympy
  - redis
  - pyyaml
  - protobuf
  - imageio
  - grpcio
  - future
  - flatbuffers
  - filelock
  - deprecated
  - click
  - autograd
  - absl-py
  - dask=2021.10.0
  - hiredis
  - pip:
    - pybamm
    - lcapy
    - scikit-spatial
    - ray