site_name: liionpack

theme:
    name: material

plugins:
- search
- mkdocstrings

docs_dir: docs

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Reference: 'reference.md'
    - Code of conduct: 'conduct.md'
    - Contributing: 'contributing.md'

