site_name: liionpack

theme:
    name: material
    palette:
      primary: blue grey
    font:
      text: Saira

strict: false

plugins:
- search
- mkdocstrings

markdown_extensions:
   - pymdownx.arithmatex

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

docs_dir: docs

nav:
    - Home: 'index.md'
    - About: 'about.md'
    - Reference: 'reference.md'
    - Code of conduct: 'conduct.md'
    - Contributing: 'contributing.md'
