# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: liionpack

on:
  push:
    branches:
  pull_request:
    branches:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  style:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        $CONDA/bin/flake8 --max-line-length=127


  build:
    needs: style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Install latex
      run: |
        sudo apt-get update
        sudo apt-get install \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-pictures
        sudo apt-get install ghostscript
    - name: Run tests and generate coverage report
      run: |
        $CONDA/bin/conda install coverage
        $CONDA/bin/coverage run -m unittest
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
