# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: liionpack

on:
  push:
    branches:
  pull_request:
    branches:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  style:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v3
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        flake8


  build:
    needs: style
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install latex
      run: |
        sudo apt-get update
        sudo apt-get install \
          texlive-latex-base \
          texlive-latex-extra \
          texlive-pictures
        sudo apt-get install ghostscript
    - name: Install liionpack
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel
        python -m pip install .
        pybamm_install_jax
    - name: Run tests and generate coverage report
      run: |
        python -m pip install coverage
        coverage run -m unittest -v
    - name: Build docs
      run: |
        python -m pip install -r docs/requirements.txt
        mkdocs build
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
